---
title: "Impact du Covid19 sur la mobilité des wallons sur vers les commerces, lieux de récréation et de travail."
author: "Huart Hugo, Liébin Arnaud, Shaw Alan, Rochet Loïc"
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
---

<!--# Ce travail doit faire entre 15 et 20 pages.-->

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

<!--% Rédigez l'introduction de ce rapport.-->

La pandémie de Covid-19 a fortement changé le quotidien des wallons. Avec les confinements, les limites de déplacement et le télétravail, les habitudes de mobilité ont été complètement bouleversées. Pour voir à quel point ces changements ont été importants, on compare la mobilité pendant la pandémie à celle d’avant les mesures, entre le 3 janvier et le 6 février 2020, une période où tout fonctionnait normalement.

## But

<!--% Rédigez le but de ce rapport.-->

Le but de ce travail est d’observer et de comprendre comment la Covid-19 a influencé la mobilité en Belgique entre 2020 et 2022. En comparant les données aux valeurs de référence, on cherche à voir comment les déplacements ont augmenté ou diminué selon les différentes périodes de la crise en se concentrant sur les commerces, les lieux de récréation et lieux de travail.

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter le données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

## Résultats

<!--% Présentez les analyses les plus pertinents que vous avez sélectionnés. Structurez la section en partie avec des titres explicites de niveau trois.-->

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->
